version: '2'
services:
  batlnext:
    image: battlestarcoin/linux-node:next
    restart: always
    networks:
      - bridge
    ports:
      - 16914:16914
    volumes:
      - batlnext:/home/batlnext/
volumes:
  batlnext:
    name: batlnext
    driver: local
