version: '2'
services:
  batlnext:
    image: ghcr.io/battlestarcoin/docker-daemon:master
    restart: always
    networks:
      - bridge
    ports:
      - 16914:16914
    volumes:
      - batlnext:/home/batlnext/
volumes:
  batlnext:
    name: batlnext
    driver: local
